// Hook tự động phát hiện task quá hạn và tạo phiếu phạt cho từng nhân viên bị giao
// Chạy reactive: mỗi khi danh sách tasks thay đổi (realtime) → kiểm tra & tạo phạt ngay
import { useEffect, useRef, useCallback } from 'react';
import { useAuth } from '../context/AuthContext';
import { useTaskConfig } from '../context/TaskConfigContext';
import { useTasks } from './useTasks';
import { useAllPenalties } from './usePenalties';
import { createPenalty } from '../firebase/firestore';
import { getTaskDisplayStatus } from '../utils/statusUtils';
import { TASK_DISPLAY_STATUS } from '../utils/constants';

export const useAutoOverduePenalties = () => {
  const { currentUser, isAdmin } = useAuth();
  const { penaltyTypes } = useTaskConfig();
  const { tasks } = useTasks();
  const { penalties } = useAllPenalties();
  const isProcessingRef = useRef(false);

  // Tìm loại phạt tự động quá hạn từ config
  const getAutoOverduePenaltyType = useCallback(() => {
    return penaltyTypes.find(pt => pt.isAutoOverdue === true) || null;
  }, [penaltyTypes]);

  // Logic chính: quét tasks quá hạn và tạo phiếu phạt ngay lập tức
  const checkAndCreateOverduePenalties = useCallback(async () => {
    // Chỉ admin mới được tự động tạo phạt
    if (!isAdmin || !currentUser) return;

    // Tránh chạy song song
    if (isProcessingRef.current) return;

    const autoType = getAutoOverduePenaltyType();
    if (!autoType) return;

    // Lọc tasks quá hạn (chưa hoàn thành, chưa bị xóa)
    const overdueTasks = tasks.filter(task => {
      if (task.isCompleted || task.isDeleted) return false;
      const status = getTaskDisplayStatus(task);
      return status === TASK_DISPLAY_STATUS.OVERDUE;
    });

    if (overdueTasks.length === 0) return;

    // Tìm các trường hợp chưa có phiếu phạt
    const penaltiesToCreate = [];
    for (const task of overdueTasks) {
      const assignees = task.assignees || [];
      for (const userId of assignees) {
        // Kiểm tra đã có phiếu phạt chưa — tránh duplicate
        const alreadyExists = penalties.some(p =>
          p.userId === userId &&
          p.taskId === task.id &&
          p.penaltyTypeId === autoType.id
        );
        if (!alreadyExists) {
          penaltiesToCreate.push({
            userId,
            taskId: task.id,
            taskTitle: task.title || 'Không rõ',
            penaltyTypeId: autoType.id,
            amount: autoType.defaultAmount || 50000,
            reason: `Tự động ghi nhận: Công việc "${task.title}" đã quá hạn deadline`,
            isAutoGenerated: true,
          });
        }
      }
    }

    if (penaltiesToCreate.length === 0) return;

    isProcessingRef.current = true;
    try {
      await Promise.all(penaltiesToCreate.map(p => createPenalty(p).catch(err => {
        console.error(`[AutoPenalty] Lỗi tạo phạt cho user ${p.userId}:`, err);
      })));
    } finally {
      isProcessingRef.current = false;
    }
  }, [isAdmin, currentUser, tasks, penalties, penaltyTypes, getAutoOverduePenaltyType]);

  // Reactive: chạy ngay khi tasks/penalties thay đổi (debounce 2s chờ data ổn định)
  useEffect(() => {
    if (!isAdmin || !currentUser || tasks.length === 0 || penaltyTypes.length === 0) return;

    const timeoutId = setTimeout(() => {
      checkAndCreateOverduePenalties();
    }, 2000);

    return () => clearTimeout(timeoutId);
  }, [isAdmin, currentUser, tasks, penalties, penaltyTypes, checkAndCreateOverduePenalties]);
};
