// Hook tự động phát hiện task quá hạn và tạo phiếu phạt cho từng nhân viên bị giao
// Chạy reactive: mỗi khi danh sách tasks thay đổi (realtime) → kiểm tra & tạo phạt ngay
import { useEffect, useRef } from 'react';
import { useAuth } from '../context/AuthContext';
import { useTaskConfig } from '../context/TaskConfigContext';
import { useTasks } from './useTasks';
import { useAllPenalties } from './usePenalties';
import { getFunctions, httpsCallable } from 'firebase/functions';
import { getTaskDisplayStatus } from '../utils/statusUtils';
import { TASK_DISPLAY_STATUS } from '../utils/constants';

export const useAutoOverduePenalties = () => {
  const { currentUser, isAdmin } = useAuth();
  const { penaltyTypes } = useTaskConfig();
  const { tasks } = useTasks();
  const { penalties } = useAllPenalties();
  const isProcessingRef = useRef(false);

  // Dùng ref để tránh stale closure — penaltyTypes cập nhật mà không cần thay đổi deps
  const penaltyTypesRef = useRef(penaltyTypes);
  useEffect(() => { penaltyTypesRef.current = penaltyTypes; }, [penaltyTypes]);

  // Reactive: chạy ngay khi tasks/penalties thay đổi (debounce 2s chờ data ổn định)
  useEffect(() => {
    if (!isAdmin || !currentUser || tasks.length === 0 || penaltyTypes.length === 0) return;

    const timeoutId = setTimeout(() => {
      // Chỉ admin mới được tự động tạo phạt
      if (isProcessingRef.current) return;

      // Đọc penaltyTypesRef.current thay vì closure cũ — tránh stale
      const currentPenaltyTypes = penaltyTypesRef.current;
      const autoType = currentPenaltyTypes.find(pt => pt.isAutoOverdue === true);
      if (!autoType) return;

      // Lọc tasks quá hạn (chưa hoàn thành, chưa bị xóa)
      const overdueTasks = tasks.filter(task => {
        if (task.isCompleted || task.isDeleted) return false;
        const status = getTaskDisplayStatus(task);
        return status === TASK_DISPLAY_STATUS.OVERDUE;
      });

      if (overdueTasks.length === 0) return;

      // Tìm các trường hợp chưa có phiếu phạt
      const penaltiesToCreate = [];
      for (const task of overdueTasks) {
        const assignees = task.assignees || [];
        for (const userId of assignees) {
          const alreadyExists = penalties.some(p =>
            p.userId === userId && p.taskId === task.id && p.penaltyTypeId === autoType.id
          );
          if (!alreadyExists) {
            penaltiesToCreate.push({
              userId,
              taskId: task.id,
              taskTitle: task.title || 'Không rõ',
              penaltyTypeId: autoType.id,
              amount: autoType.defaultAmount || 50000,
              reason: `Tự động ghi nhận: Công việc "${task.title}" đã quá hạn deadline`,
              isAutoGenerated: true,
            });
          }
        }
      }

      if (penaltiesToCreate.length === 0) return;
      isProcessingRef.current = true;

      const functions = getFunctions();
      const createPenaltyIdempotent = httpsCallable(functions, 'createPenaltyIdempotent');

      Promise.allSettled(
        penaltiesToCreate.map(p =>
          createPenaltyIdempotent({
            userId: p.userId,
            taskId: p.taskId,
            taskTitle: p.taskTitle,
            penaltyTypeId: p.penaltyTypeId,
            amount: p.amount,
            reason: p.reason,
          })
        )
      )
        .then(results => {
          const failed = results.filter(r => r.status === 'rejected');
          if (failed.length > 0) {
            console.warn('Một số phiếu phạt không tạo được:', failed);
          }
        })
        .finally(() => { isProcessingRef.current = false; });
    }, 2000);

    return () => clearTimeout(timeoutId);
  }, [isAdmin, currentUser, tasks, penalties]);
};
